name: Create Blank Issue
description: Blank issue report for Feather: Stik Edition, our developer testing tool. Use this for anything other than a bug or feature request.

body:
  - type: markdown
    attributes:
      value: >-
        Make sure you read the [Code of
        Conduct](https://github.com/khcrysalis/Feather/blob/main/CODE_OF_CONDUCT.md)
        before making an issue, and make sure there aren't already the same bug
        reported.

  - type: textarea
    id: text
    attributes:
      label: Content
    validations:
      required: true

  - type: checkboxes
    id: agreement
    attributes:
      label: Request Agreement
      options:
        - label: I have read the requirements for opening an issue above
          required: true
